### ISSUE TITLE
"load_model" Error in VAE

### ISSUE THREAD

**Issue by TsaiYunLin** [chaitanya100100/VAE#5]
Recently, I run this code...
When I running load_model in following line it gives me a error 
**"ValueError: When passing a list as loss, it should have one entry per model outputs. The model has 1 outputs, but you passed loss=[]"**  
Did somebody know how to fix it? I realize that the reason of error is obviously but I couldn't come up with good solutions.  TKS. 
https://github.com/chaitanya100100/VAE-for-Image-Generation/blob/1c4be4eaed969a3b634a0edd8a2a90a99569146c/src/mnist_2d_latent_space_and_generate.py#L46

p.s. I just found one possible solution in Example of Keras GitHub: Just use load_weight & save_weight. TKS.
https://github.com/keras-team/keras/blob/ad578c4c19444af9d1f0e0d51a8283eb0db1a264/examples/variational_autoencoder.py#L202

**Comment by vytkri** [comment]
I've found a workaround [here](https://github.com/keras-team/keras/issues/10417).

basically, downgrade to ```keras 2.1.0```
